import re

# ulica=re.compile('m\.')
ulica = re.compile('\sm\..*')
ulica_else = re.compile('\d+\s?\.\s?([^,]+)\s?,\s?([^\d]+)\s?((?!m\.).*)\s?\(.*')
X = re.compile('Sprzedał\s?:\s?(.*)\s+-.*')
Y = re.compile('Typ\s?właś.*\s?:\s?(osoba fizyczna|\s?osoba\s?fizyczna|\s?osoba\s?prawna|gmina|\s?gmina\s?|\s?Skarb\s?Państwa\s?)',re.IGNORECASE)
B = re.compile('.*określono\s?[wW]\s?dniu\s?(.*)')
H = re.compile('.*Obręb\s?:\s?\d{2}(\d{2})\s?-\s?([^,]+),\s?Ark\.:\s?\\b(.*)(?=\s?,\s?Nr\s?dz\.)\s?,\s?Nr\s?dz\.:\s?(.*?)(?=\s?Liczba\s?izb)\s?Liczba\s?izb\s?:\s?(\d{1})\s?(.*?)\s?(?=(\s?\d+?Funkcja|\s?Funkcja)).*',re.DOTALL)
# H = re.compile('.*Obręb\s?:\s?\d{2}(\d{2})\s?-\s?([^,]+),\s?Ark\.:\s?\\b(.*)(?=\s?,\s?Nr\s?dz\.)\s?,\s?Nr\s?dz\.:\s?([^Liczba]+)\s?Liczba\s?izb\s?:\s?(\d{1})\s?(.*?)\s?(?=(\s?\d+?Funkcja|\s?Funkcja)).*')
J = re.compile('\d+\s?\.\s?([^,]+)\s?,\s?([^\d]+)\s?((?!m\.).*)\s?m\.\s?([^(\s]+)\s?.*')
# M = re.compile('.*Pow\.\s?użytk\.\s?:\s?([^m\s]+)\s?.*')
M = re.compile('.*Pow\.\s?użytk\.\s?:\s?\\b(.*)(?=\s?m\s?kw\.).*')
N = re.compile('.*Cena\s?łączna\snieruchomości\s?:\s?\\b([^zł]+)(?=\s?z?ł?\s?okre).*')
V = re.compile('Rodzaj\s?bud\.\s?:\s?(jednorodzinne|wielorodzinne|wieIorodzinne)')
CB = re.compile('.*Pow\.\s?:\s?(.*)\sha.*')
AH = re.compile('.*Nr\s?dok\.\s?:\s?([a-zA-Z]+)-?\s?(\d+/\d+).*')
Z = re.compile('.*Opis\s?dodatkowy\s?:\s?(.*)',re.S)
Z_uwagi_do_ceny = re.compile('.*Uwagi\s?do\s?ceny\s?:\s?(.*?)(?=\s?Nr\s?dok).*',re.S)
AF = re.compile('.*KW\s?:\s?(.*)')
